---
- name: Request IDE information
  ansible.builtin.uri:
    url: '{{ jetbrains_releases_url }}?code={{ jetbrains_ide | map(attribute="code") | join(",") }}'
  register: releases

- name: Install ide
  ansible.builtin.include_tasks:
    file: setup.yml
  with_items: '{{ jetbrains_ide }}'
  loop_control:
    loop_var: ide
