---
- name: Verify installation mode
  ansible.builtin.assert:
    that: 'jetbrains_ide_installation_mode | lower in [ "system", "user" ]'
    msg: 'Invalid installation mode, valid ones: "system", "user"'

- name: Source installation mode specific variables
  ansible.builtin.include_vars: '{{ jetbrains_ide_installation_mode | lower }}.yml'

- name: Ensure jmsepath is installed
  ansible.builtin.pip:
    name: jmespath
  delegate_to: 127.0.0.1

- name: Install ide
  ansible.builtin.include_tasks:
    file: install.yml
  with_items: '{{ jetbrains_ide }}'
  loop_control:
    loop_var: outer_item
