---
- name: Verify installation mode
  ansible.builtin.assert:
    that: 'jetbrains_ide_installation_mode in [ "system", "user" ]'
    msg: 'Invalid installation mode, valid ones: "system", "user"'

- name: Request Ide information
  ansible.builtin.uri:
    url: '{{ jetbrains_ide_releases_url }}?code={{ jetbrains_ide_info[jetbrains_ide].code }}&type=release'
  register: ide_releases_response

- name: Get releases versions list
  ansible.builtin.set_fact:
    ide_available_versions: '{{ ide_releases_response.json[jetbrains_ide_info[jetbrains_ide].code] | map(attribute="version")  }}'

- name: Verify selected version is valid
  ansible.builtin.assert:
    that: 'jetbrains_ide_version | string  in ide_available_versions'
    msg: 'Ide version {{ jetbrains_ide_version }} does not exist, availables ones are: {{ ide_available_versions }}'
  when: jetbrains_ide_version != 'latest'

- name: Get latest available version
  ansible.builtin.set_fact:
    ide_version: '{{ ide_available_versions | first }}'
  when: jetbrains_ide_version | lower == 'latest'

- name: Download and verify ide tarball
  ansible.builtin.get_url:
    url: '{{ ide_releases_response.json | community.general.json_query(ide_url_query) | first }}'
    dest: '{{ jetbrains_ide_local_download_dir }}/{{ jetbrains_ide }}.tar.gz'
    checksum: 'sha256:{{ ide_releases_response.json | community.general.json_query(ide_hash_url_query) | first }}'
  vars:
    ide_url_query:  "{{ jetbrains_ide_info[jetbrains_ide].code}}[?version == '{{ jetbrains_ide_version }}'].downloads.linux.link"
    ide_hash_url_query: "{{ jetbrains_ide_info[jetbrains_ide].code }}[?version == '{{ jetbrains_ide_version }}'].downloads.linux.checksumLink"
  delegate_to: 127.0.0.1

- name: Determine unpack and launcher directories
  ansible.builtin.set_fact:
    ide_unpack_dir: '{{ (jetbrains_ide_installation_mode == "system") | ternary("/opt", "~/.local/opt") }}'
    ide_launcher_dir: '{{ (jetbrains_ide_installation_mode == "system") | ternary("/usr/local/share/applications", "~/.local/share/applications") }}'

- name: Ensure directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
  loop:
    - '{{ ide_unpack_dir }}/{{ jetbrains_ide }}'
    - '{{ ide_launcher_dir }}'

- name: Extract tarball
  ansible.builtin.unarchive:
    src: '{{ jetbrains_ide_local_download_dir }}/{{ jetbrains_ide }}.tar.gz'
    dest: '{{ ide_unpack_dir }}/{{ jetbrains_ide }}'
    extra_opts:
      --strip-components=1

- name:
  ansible.builtin.template:
    src: templates/launcher.desktop.j2
    dest: '{{ ide_launcher_dir }}/{{ jetbrains_ide }}.desktop'
