---
- name: Request IDE information
  ansible.builtin.uri:
    url: '{{ jetbrains_products_url }}?code={{ jetbrains_ide_code }}'
  delegate_to: localhost
  register: products

- name: Verify requested IDE version is valid
  ansible.builtin.assert:
    that: 'jetbrains_ide_version in ide_available_versions'
    msg: 'version {{ jetbrains_ide_version }} not found, availables ones are: {{ ide_available_versions }}'
  vars:
    ide_available_versions: '{{ products.json.0.releases | map(attribute="version") }}'
  delegate_to: localhost

- name: Download tarball
  ansible.builtin.get_url:
    url: '{{ product.link }}'
    dest: '{{ jetbrains_local_download_dir }}/{{ product.link | basename }}'
    checksum: sha256:{{ product.checksumLink }}
  vars:
    product: '{{ (products.json.0.releases | selectattr("version", "eq", jetbrains_ide_version) | first).downloads.linux }}'
  delegate_to: localhost
  register: downloaded_tarball

- name: Ensure installation directory exists on target
  ansible.builtin.file:
    path: '{{ jetbrains_installation_dir }}'
    state: directory
    owner: '{{ jetbrains_user }}'
    group: '{{ jetbrains_user }}'
    mode: '755'

- name: Extract tarball
  ansible.builtin.unarchive:
    src: '{{ downloaded_tarball.dest }}'
    dest: '{{ jetbrains_installation_dir }}'
    list_files: true
    remote_src: false
  register: extracted_tarball

- name: Read product-info.json
  ansible.builtin.slurp:
    src: '{{ jetbrains_installation_dir }}/{{ extracted_tarball.files.0 }}/product-info.json'
  register: read_product_info

- name: Create launcher and link to executable
  vars:
    product_info: '{{ read_product_info.content | b64decode | from_json }}'
  block:
    - name: Ensure desktop launcher exists
      ansible.builtin.template:
        src: templates/launcher.desktop.j2
        dest: '{{ jetbrains_launcher_dir }}/{{ product_info.launch.0.startupWmClass }}.desktop'
        owner: '{{ jetbrains_user }}'
        group: '{{ jetbrains_user }}'
        mode: '644'

    - name: Ensure link to executable exists
      ansible.builtin.file:
        src: '{{ jetbrains_installation_dir }}/{{ extracted_tarball.files.0 }}/{{ product_info.launch.0.launcherPath }}'
        dest: '{{ jetbrains_binary_dir }}/{{ product_info.name | lower }}'
        state: link
        owner: '{{ jetbrains_user }}'
        group: '{{ jetbrains_user }}'
      when: jetbrains_link_executable | bool
