---
- name: Register IDE available versions
  ansible.builtin.set_fact:
    ide_available_versions: '{{ releases.json[ide.code] | map(attribute="version") }}'

- name: Verify requested IDE version is valid
  ansible.builtin.assert:
    that: 'ide.version in ide_available_versions'
    msg: 'version {{ ide.version }} not found, availables ones are: {{ ide_available_versions }}'
  when: ide.version | lower != 'latest'

- name: Set IDE effective version
  ansible.builtin.set_fact:
    ide_effective_version: '{{ (ide.version == "latest") | ternary(ide_available_versions | first, ide.version) }}'
