---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rockylinux-9
    image: docker.io/rockylinux:9
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
