---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    desktop_launcher_content: |-
      [Desktop Entry]
      Version=1.0
      Type=Application
      Name=PhpStorm
      Icon=/opt/phpstorm/bin/phpstorm.svg
      Exec="/opt/phpstorm/bin/phpstorm.sh" %f
      Comment=Lightning-Smart PHP IDE
      Categories=Development;IDE
      Terminal=false
      StartupWMClass=jetbrains-phpstorm
      Keywords=programming;programmer;development;developer;code;
      StartupNotify=true

  tasks:
    - name: Check Ide executable
      block:
        - name: stat /opt/phpstorm/bin/phpstorm.sh
          ansible.builtin.stat:
            path: /opt/phpstorm/bin/phpstorm.sh
          register: ide_executable

        - name: Check if /opt/phpstorm/bin/phpstorm.sh is in place
          ansible.builtin.assert:
            that:
              - ide_executable.stat.exists == true

    - name: Check Ide desktop launcher
      block:
        - name: stat /usr/local/share/applications/phpstorm.desktop
          ansible.builtin.stat:
            path: /usr/local/share/applications/phpstorm.desktop
          register: ide_desktop_file

        - name: Check if /usr/local/share/applications/phpstorm.desktop exists
          ansible.builtin.assert:
            that:
              - ide_desktop_file.stat.exists == true

    - name: Check launcher content is as expected
      block:
        - ansible.builtin.shell: cat /usr/local/share/applications/phpstorm.desktop
          register: cat
        - ansible.builtin.assert:
            that: '{{ cat.stdout == desktop_launcher_content }}'
